[package]
name = "tnotes-document"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0.20"
ulid = { version = "3.0", features = ["serde"] }
pulldown-cmark = { version = "0.13", default-features = false, features = ["simd"] }

[dev-dependencies]
pretty_assertions = "1.4"
