[package]
name = "tnotes-server"
version = "0.1.0"
edition = "2024"

[dependencies]
tnotes-core = { path = "../crates/tnotes-core" }

axum = { version = "0.8.1", features = ["ws"] }
tokio = { version = "1.43.0", features = ["full"] }
tower = { version = "0.5.2", features = ["util"] }
tower-http = { version = "0.6.2", features = ["cors", "compression-gzip", "trace"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "json"] }
validator = { version = "0.20.0", features = ["derive"] }
qrcode-generator = "5.0.0"
futures-util = "0.3.31"
axum-extra = { version = "0.10.0", features = ["cookie"] }
time = "0.3"
rust-embed = "8.5.0"
mime_guess = "2.0.5"

[dev-dependencies]
http-body-util = "0.1.2"
tokio-tungstenite = "0.26.2"
reqwest = { version = "0.12.12", features = ["json"] }
