allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@expo/cli@57.0.20 || 57.0.22 || 57.0.25 || 57.0.26'
  - '@expo/env@2.4.3'
  - '@expo/fingerprint@0.20.11'
  - '@expo/metro-config@57.0.12'
  - expo-constants@57.0.16 || 57.0.19
  - expo-font@57.0.2
  - expo@57.0.18 || 57.0.20 || 57.0.23 || 57.0.24
  - '@expo/ui@57.0.16 || 57.0.19'
  - expo-modules-core@57.0.16
  - expo-modules-jsi@57.0.8
  - expo-router@57.0.19 || 57.0.22
  - expo-sharing@57.0.18 || 57.0.20 || 57.0.21
  - '@expo/router-server@57.0.10'
  - babel-preset-expo@57.0.12
  - expo-asset@57.0.18
  - '@expo/metro-runtime@57.0.16'
overrides:
  react-dom: "19.2.3"
  react: "19.2.3"
