use crate::components::icons::*;
use gpui::*;

pub fn system_section() -> impl IntoElement {
    div()
        .flex()
        .flex_col()
        .gap_0p5()
        .child(
            div()
                .px_2()
                .pt_2()
                .pb_1()
                .text_xs()
                .font_weight(FontWeight::BOLD)
                .text_color(rgb(0x79747e))
                .child("SYSTEM"),
        )
        .child(
            div()
                .id("system-archive")
                .flex()
                .items_center()
                .justify_between()
                .px_2()
                .py_1p5()
                .rounded_md()
                .hover(|s| s.bg(rgb(0x201f24)))
                .cursor_pointer()
                .child(
                    div()
                        .flex()
                        .items_center()
                        .gap_2p5()
                        .child(
                            div()
                                .w_4()
                                .h_4()
                                .child(icon_archive().size_4().text_color(rgb(0x938f99))),
                        )
                        .child(
                            div()
                                .text_xs()
                                .font_weight(FontWeight::MEDIUM)
                                .text_color(rgb(0xe6e1e9))
                                .child("Archive"),
                        ),
                ),
        )
        .child(
            div()
                .id("system-trash")
                .flex()
                .items_center()
                .justify_between()
                .px_2()
                .py_1p5()
                .rounded_md()
                .hover(|s| s.bg(rgb(0x201f24)))
                .cursor_pointer()
                .child(
                    div()
                        .flex()
                        .items_center()
                        .gap_2p5()
                        .child(
                            div()
                                .w_4()
                                .h_4()
                                .child(icon_trash().size_4().text_color(rgb(0x938f99))),
                        )
                        .child(
                            div()
                                .text_xs()
                                .font_weight(FontWeight::MEDIUM)
                                .text_color(rgb(0xe6e1e9))
                                .child("Trash"),
                        ),
                )
                .child(
                    div()
                        .text_xs()
                        .text_color(rgb(0x938f99))
                        .child("0"),
                ),
        )
        .child(
            div()
                .id("system-assets")
                .flex()
                .items_center()
                .justify_between()
                .px_2()
                .py_1p5()
                .rounded_md()
                .hover(|s| s.bg(rgb(0x201f24)))
                .cursor_pointer()
                .child(
                    div()
                        .flex()
                        .items_center()
                        .gap_2p5()
                        .child(
                            div()
                                .w_4()
                                .h_4()
                                .child(icon_paperclip().size_4().text_color(rgb(0x938f99))),
                        )
                        .child(
                            div()
                                .text_xs()
                                .font_weight(FontWeight::MEDIUM)
                                .text_color(rgb(0xe6e1e9))
                                .child("Assets"),
                        ),
                ),
        )
}
