use crate::components::icons::*;
use crate::state::AppState;
use gpui::*;

pub fn appearance_tab(_app_state: Entity<AppState>, _cx: &mut App) -> impl IntoElement {
    div()
        .id("settings-appearance-screen")
        .flex_1()
        .h_full()
        .overflow_y_scroll()
        .p_8()
        .flex()
        .flex_col()
        .items_center()
        .child(
            div()
                .w_full()
                .max_w(px(680.0))
                .flex()
                .flex_col()
                .gap_8()
                // 1. Theme Section
                .child(
                    div()
                        .flex()
                        .flex_col()
                        .gap_3()
                        .child(section_title("THEME"))
                        .child(
                            div()
                                .flex()
                                .flex_col()
                                .gap_4()
                                // Dark Mode Row
                                .child(
                                    div()
                                        .flex()
                                        .items_center()
                                        .justify_between()
                                        .py_1()
                                        .child(
                                            div()
                                                .flex()
                                                .items_center()
                                                .gap_3()
                                                .child(icon_moon().size_5().text_color(rgb(0xcabeff)))
                                                .child(
                                                    div()
                                                        .flex()
                                                        .flex_col()
                                                        .gap_0p5()
                                                        .child(
                                                            div()
                                                                .text_xs()
                                                                .font_weight(FontWeight::SEMIBOLD)
                                                                .text_color(rgb(0xe6e1e9))
                                                                .child("Dark Mode"),
                                                        )
                                                        .child(
                                                            div()
                                                                .text_xs()
                                                                .text_color(rgb(0x938f99))
                                                                .child("Dark theme enabled"),
                                                        ),
                                                ),
                                        )
                                        .child(
                                            div()
                                                .id("btn-toggle-darkmode")
                                                .flex()
                                                .items_center()
                                                .px_2p5()
                                                .py_1()
                                                .rounded_full()
                                                .border_1()
                                                .border_color(rgb(0xa6e3a1))
                                                .bg(rgb(0x1e3a2f))
                                                .child(
                                                    div()
                                                        .text_xs()
                                                        .font_weight(FontWeight::SEMIBOLD)
                                                        .text_color(rgb(0xa6e3a1))
                                                        .child("Dark"),
                                                ),
                                        ),
                                )
                                .child(div().h_px().bg(rgb(0x201f24)))
                                // Accent Color Row
                                .child(
                                    div()
                                        .flex()
                                        .items_center()
                                        .justify_between()
                                        .py_1()
                                        .child(
                                            div()
                                                .flex()
                                                .items_center()
                                                .gap_3()
                                                .child(icon_palette().size_5().text_color(rgb(0xcabeff)))
                                                .child(
                                                    div()
                                                        .flex()
                                                        .flex_col()
                                                        .gap_0p5()
                                                        .child(
                                                            div()
                                                                .text_xs()
                                                                .font_weight(FontWeight::SEMIBOLD)
                                                                .text_color(rgb(0xe6e1e9))
                                                                .child("Accent Color"),
                                                        )
                                                        .child(
                                                            div()
                                                                .text_xs()
                                                                .text_color(rgb(0x938f99))
                                                                .child("Interface highlights and primary accents"),
                                                        ),
                                                ),
                                        )
                                        .child(
                                            div()
                                                .flex()
                                                .items_center()
                                                .gap_2()
                                                .px_2p5()
                                                .py_1()
                                                .rounded_full()
                                                .border_1()
                                                .border_color(rgb(0x302e36))
                                                .child(div().w_2p5().h_2p5().rounded_full().bg(rgb(0xcabeff)))
                                                .child(
                                                    div()
                                                        .text_xs()
                                                        .font_weight(FontWeight::MEDIUM)
                                                        .text_color(rgb(0xe6e1e9))
                                                        .child("Lavender Purple"),
                                                ),
                                        ),
                                ),
                        ),
                )
                // 2. Typography Section
                .child(
                    div()
                        .flex()
                        .flex_col()
                        .gap_3()
                        .child(section_title("TYPOGRAPHY"))
                        .child(
                            div()
                                .flex()
                                .items_center()
                                .justify_between()
                                .py_1()
                                .child(
                                    div()
                                        .flex()
                                        .items_center()
                                        .gap_3()
                                        .child(icon_type().size_5().text_color(rgb(0xcabeff)))
                                        .child(
                                            div()
                                                .flex()
                                                .flex_col()
                                                .gap_0p5()
                                                .child(
                                                    div()
                                                        .text_xs()
                                                        .font_weight(FontWeight::SEMIBOLD)
                                                        .text_color(rgb(0xe6e1e9))
                                                        .child("Font Family"),
                                                )
                                                .child(
                                                    div()
                                                        .text_xs()
                                                        .text_color(rgb(0x938f99))
                                                        .child("System native UI typography"),
                                                ),
                                        ),
                                )
                                .child(
                                    div()
                                        .text_xs()
                                        .font_weight(FontWeight::MEDIUM)
                                        .text_color(rgb(0x79747e))
                                        .child("System Default"),
                                ),
                        ),
                ),
        )
}

fn section_title(label: &'static str) -> impl IntoElement {
    div()
        .text_xs()
        .font_weight(FontWeight::BOLD)
        .text_color(rgb(0x79747e))
        .child(label)
}
